services:
  backend:
    container_name: backend
    build: backend
    ports:
      - "8000:8000"
    environment:
      - SCRAPER_URL=http://scraper:8000
      - COLOR_SEARCH_URL=http://color_search:8000
      - IMAGE_BLENDER_URL=http://image_blender:8000
    volumes:
      - ./config:/app/config
      - ./backend/src:/app/src
  scraper:
    container_name: scraper
    build: scraper
    ports:
      - "8001:8000"
    volumes:
      - ./config:/app/config
      - ./scraper/src:/app/src
      - ./db:/app/db
      - ./img:/app/img
  color_search:
    container_name: color_search
    build: color-search
    ports:
      - "8002:8000"
    volumes:
      - ./config:/app/config
      - ./color-search/src:/app/src
      - ./db:/app/db
      - ./img:/app/img
  image-processer:
    container_name: image-processer
    build: image-processer
    volumes:
      - ./config:/app/config
      - ./image-processer/src:/app/src
      - ./db:/app/db
      - ./img:/app/img
      - ./processed_img:/app/processed_img
  image-blender:
    container_name: image-blender
    build: image-blender
    ports:
      - "8003:8000"
    volumes:
      - ./config:/app/config
      - ./image-blender/src:/app/src
